import UIKit
import UserNotifications
import Foundation

struct Booking {
    let date: Date
    let location: String
    let numberOfGuests: Int
    let price: Double
    let user: User

    func confirm() {
        print("Booking confirmed for date: \(date), location: \(location), number of guests: \(numberOfGuests), price: $\(price)")
    }
}

class User {
    let username: String
    let password: String
    var email: String?
    var phoneNumber: String?

    init(username: String, password: String) {
        self.username = username
        self.password = password
    }

    func login(username: String, password: String) -> Bool {
        if username == self.username && password == self.password {
            print("Login successful for user: \(username)")
            return true
        } else {
            print("Login failed for user: \(username)")
            return false
        }
    }

    func updateProfile(email: String? = nil, phoneNumber: String? = nil) {
        if let email = email {
            self.email = email
        }

        if let phoneNumber = phoneNumber {
            self.phoneNumber = phoneNumber
        }
    }
}

class BookingViewController: UIViewController {
    let booking = Booking(date: Date(), location: "New York", numberOfGuests: 2, price: 199.99, user: User(username: "user1", password: "password"))

    func searchBookings(location: String? = nil, date: Date? = nil, numberOfGuests: Int? = nil, price: Double? = nil) -> [Booking] {
        var searchResults: [Booking] = []

        if let location = location {
            searchResults = searchResults.filter { $0.location == location }
        }

        if let date = date {
            searchResults = searchResults.filter { $0.date == date }
        }

        if let numberOfGuests = numberOfGuests {
            searchResults = searchResults.filter { $0.numberOfGuests == numberOfGuests }
        
        if let price = price {
            searchResults = searchResults.filter { $0.price == price }
        }

        return searchResults
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        let orangeThemeColor = UIColor(red: 1.0, green: 0.5, blue: 0.0, alpha: 1.0)
        view.backgroundColor = orangeThemeColor
        navigationController?.navigationBar.barTintColor = orangeThemeColor
    
    @IBAction func confirmButtonTapped(_ sender: Any) {
        if booking.user.login(username: "user1", password: "password") {
            booking.confirm()
